#baseURL = 'https://bnyounes17.github.io/HugoSite/'
#baseURL = "http://hugowebsite-ybn.s3-website.us-east-2.amazonaws.com/"
baseURL = "https://d17h462cczkjl4.cloudfront.net/"
languageCode = 'en-us'
title = 'Younes Bensassi-Nour'
theme ="ananke"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "About"
    url = "/welcome/"
    weight = 2
    
  [[menu.main]]
    name = "Projects"
    url = "/post/"
    weight = 3
  
  [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 4
  
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
